Todo-devise/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "todos", to: "todos#index"
  get "todos/new", to: "todos#new"
  post "todos", to: "todos#create"
  get "todos/:id", to: "todos#show", as: :todo
  get "todos/:id/edit", to: "todos#edit", as: :edit_todo
  patch "todos/:id", to: "todos#update"
  delete "todos/:id", to: "todos#destroy", as: :delete_todo
  root to: "todos#index"
end

Todo-devise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Todo-devise/app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
end

Todo-devise/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todos
end

Todo-devise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Todo-devise/app/controllers/todos_controller.rb
class TodosController < ApplicationController
	  before_action :authenticate_user!

	def index
		@todos = Todo.where(user_id: current_user.id)
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.user = current_user
		@todo.save
		redirect_to todos_path
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end


	private

	def todo_params
		params.require(:todo).permit(:title, :content)
	end

end

Todo-devise/app/helpers/application_helper.rb
module ApplicationHelper
end

Todo-devise/app/helpers/todos_helper.rb
module TodosHelper
end

Todo-devise/app/views/layouts/application.html.erb
  <title>TODO LIST APP</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path , class: "btn "%></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path, class: "btn "  %></li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn " %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "btn " %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

Todo-devise/app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
<%= f.label :title, 'Title' %>
<%= f.text_field :title %>
<br>
<%= f.label :content, 'Content' %>
<%= f.text_area :content %>
<br>
 <%= f.submit %>
<% end %>

Todo-devise/app/views/todos/edit.html.erb
<h1> Editing a post </h1>
<%= render 'todos/form' %>

Todo-devise/app/views/todos/index.html.erb
<h1>All Todos</h1>
<%= link_to "New Todo", todos_new_path %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      	<tr>
        <td><%= todo.title %></td>
        <td><%= todo.content %></td>
        <td><%= link_to "Show", todo %></td>
        <td><%= link_to "Edit", edit_todo_path(todo) %></td>
        <td><%= link_to "Destroy", delete_todo_path(todo), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %></td>
        </tr>
    <% end %>

  </tbody>
</table>

Todo-devise/app/views/todos/new.html.erb
<h1> Creating a new post </h1>
<%= render 'todos/form' %>

Todo-devise/app/views/todos/show.html.erb
<p>
<strong>Title</strong>
<%= @todo.title %>
</p>

<p>
<strong>Content</strong>
<%= @todo.content %>
</p>

Todo-devise/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Todo-devise/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>